In [2]:
import numpy as np
x = np.array([1,2,3,4])
M = np.arange(6).reshape(2,3)
print(M)
print(x.shape,M.shape)

[[0 1 2]
 [3 4 5]]
(4,) (2, 3)


In [3]:
y = np.array([10,20,30,40])
print(x+y,x*y,x ** 2)
print(x @ y)
print(np.sqrt(x), np.abs(np.array([-3,2])))

[11 22 33 44] [ 10  40  90 160] [ 1  4  9 16]
300
[1.         1.41421356 1.73205081 2.        ] [3 2]


In [4]:
print(M.sum(),M.max(),M.mean())
print(M.sum(axis=0))
print(M.sum(axis=1))
print(M.sum(axis=1,keepdims=True).shape)

15 5 2.5
[3 5 7]
[ 3 12]
(2, 1)


In [6]:
A=np.arange(12).reshape(3,4)
print(A)
print(A[0])        # строка
print(A[2, 1])     # элемент: строка 2, столбец 1
print(A[:, 0])     # все строки, столбец 0
print(A[-1])       # последняя строка
print(A[0, 1:3])   # срез start:stop, stop не включается
print(A[:, ::3])   # шаг 3
print(A[A % 2 == 0])   # булева маска: только чётные элементы

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
9
[0 4 8]
[ 8  9 10 11]
[1 2]
[[ 0  3]
 [ 4  7]
 [ 8 11]]
[ 0  2  4  6  8 10]


In [10]:
A=np.arange(6).reshape(2,3)
print(A + 100)
print(A+np.array([10,20,30]))
print(A + np.array([[100], [200]]))

[[100 101 102]
 [103 104 105]]
[[10 21 32]
 [13 24 35]]
[[100 101 102]
 [203 204 205]]


In [33]:
a = np.array([1,2,3])
b = np.array([4,5,6])

def check_sum(a,b):
    total_sum = 0
    for item in a:
        total_sum += item*b 
    return total_sum
print(a@b)
print(check_sum(a,b))


32
[24 30 36]


In [36]:
import math
v = np.array([3,4])
def l1_norm(v):
    return (v ** 2)
def l2_norm(v):
    return math.sqrt(sum(x ** 2 for x in  v))
print(l1_norm(v))
print(l2_norm(v))
print(np.linalg.norm(v, ord = 1))
print(np.linalg.norm(v,ord = 2))


[ 9 16]
5.0
7.0
5.0


In [48]:
a = np.array([1,2])
b = np.array([2,4])
def cosine_sum(a,b):
    return a@b/(np.linalg.norm(a) * np.linalg.norm(b))
print(cosine_sum(a,b))

0.9999999999999998


In [55]:
M = np.arange(20).reshape(4,5)
print(M[1])
print(M[:,-1])
print(M[M > 10])
print(M[:,::2])


[5 6 7 8 9]
[ 4  9 14 19]
[11 12 13 14 15 16 17 18 19]
[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]]


In [63]:
X = np.random.randn(100,3) * 5 + 10
print((X - X.std(axis = 0))/np.linalg.norm(X))

[[ 6.38421797e-02  8.28141193e-02 -2.38500040e-02]
 [ 2.01507621e-02  5.10319057e-02  4.63646092e-04]
 [ 4.88587448e-02  3.87517477e-02  2.66207879e-02]
 [-1.24590807e-02  6.07690920e-03  2.05913076e-02]
 [ 2.17102464e-02  3.91685671e-02  3.10200536e-02]
 [ 2.27694967e-02  1.46605841e-02  5.92400493e-02]
 [ 4.98174275e-02  2.19230847e-02  3.34507361e-03]
 [ 3.38668914e-02  7.41161217e-02  7.83588760e-02]
 [ 1.95919432e-02  2.74168601e-02  5.16379451e-02]
 [ 3.33570535e-02  1.55535411e-02  4.89841516e-02]
 [ 2.83363660e-02  4.68346864e-02  2.85812444e-02]
 [ 1.65551737e-02 -1.71123111e-02  5.35532330e-04]
 [ 1.74543337e-02 -2.38232133e-02  1.90067700e-02]
 [ 4.01303843e-02  3.99927183e-02  4.14946769e-02]
 [ 4.24034420e-02  3.53697381e-02  1.20608100e-02]
 [-4.48468054e-03  5.95320594e-02  2.02869899e-02]
 [ 5.92450175e-02  8.59658091e-02  2.64818794e-02]
 [ 1.81236524e-02  4.52138518e-02 -5.12969213e-03]
 [ 3.24912160e-02 -2.29301457e-02  5.13843447e-02]
 [ 4.91298487e-02  5.74189181e-

In [75]:
length = np.linalg.norm(X,axis = 1,keepdims = True)
norm = X / length
print(np.linalg.norm(norm,axis = 1))



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [88]:


def loop_sum():
    a = 1000001
    b = 0
    for i in range(a):
        b += (i**2)
    return b
%timeit loop_sum()

def loop_sum_numpy():
    X = np.arange(0,1000001)
    result = (X**2).sum()
    return result
%timeit loop_sum_numpy()

110 ms ± 6.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
5.18 ms ± 301 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [92]:
print((np.ones(3) + np.ones((3,1))).shape)
"""
на выходе мы получаем форму 3 3, потому что единица из  
второго массива растянулась до 3
ось 0 ось 1
1       3
3       1
↓       ↓       
3       3 
"""
  

(3, 3)


'\nна выходе мы получаем форму 3 3, потому что единица из  \nвторого массива растянулась до 3\nось 0 ось 1\n1       3\n3       1\n↓       ↓       \n3       3 \n'